### PR TITLE
Fix RebootToAndroid

### PR DESCRIPTION
**Pull request by showkubii**

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Having a hidden button for one single platform specific action is a bad idea.

**Comment by showkubii** [comment]
> Having a hidden button for one single platform specific action is a bad idea.

RebootToAndroid, It's for CoreELEC or LibreELEC only, which makes no sense to show on other platforms.

**Comment by showkubii** [comment]
I'll just try to fix it again.

**Comment by showkubii** [comment]
I tried to fix it and only this method can work properly.

**Comment by jurialmunkey** [comment]
I'm saying that using a hidden button to perform one particular action that is only relevant for one platform is a bad idea. You will need to find a different method.

**Comment by showkubii** [comment]
> I'm saying that using a hidden button to perform one particular action that is only relevant for one platform is a bad idea. You will need to find a different method.

I didn't hide the button.

If you can't include it, that's fine. RebootToAndroid It doesn't work properly, I have to press the button. RebootToAndroid and press the Reboot button again to go back to Android.

**Comment by jurialmunkey** [comment]
I'm saying using a button to do this command is a bad approach. You can't add buttons for every command that needs two actions. You need to find a different way to do the two actions without relying on sending focus to a button. There are lots of ways this could be done using skinshortcuts templates rather than scattering random controls everywhere

**Pull request closed without merging**
