### PR TITLE
add duration to footer and more viewtypes to files view

### PR DESCRIPTION
**Pull request by skittles9823**
Wall and List viewtypes work well in files view when using it to view locally saved videos like YouTube videos or Twitch VODs without having to assign a content type for a source (which allows you to have different viewtypes for say tv shows and a downloaded youtube source)

Adding the video duration to the footer in the files view works well with this change

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Duration should not go in the footer. Duration goes in the info line.

**Comment by skittles9823** [comment]
Anything else you'd like changed or?

**Comment by jurialmunkey** [comment]
Sorry, I missed the notification that you'd updated the PR. Didn't realise this has been sitting here for two weeks!

For the info line, there's already a duration label a little further up. You just need to expand the condition to check for an empty dbtype.

One other note - shouldn't use Container.Content() as a condition in the info line. The info displayed relates to the focused ListItem. The container content is irrelevant (and also won't work on Home screen). What is relevant is the DBType of the ListItem.

You should be able to check for an empty DBType (i.e. no source type set) by using 
`String.IsEmpty($PARAM[container]ListItem.DBType)`

**Comment by jurialmunkey** [comment]
> I opted to add a new condition to make the duration verbose with seconds also showing

Are seconds necessary? I'm not sure how much it helps to make a decision about what to watch and I'd prefer consistency of style.

**Comment by skittles9823** [comment]
Oops pushed a merge commit. #555 should be cleaner anyway as It's a single commit now

**Pull request closed without merging**
