### PR TITLE
Adding an Arabic Translation for AH2

### PR DESCRIPTION
**Pull request by psp2111-ADSLGATE**
Hi @jurialmunkey 
this is an Arabic translation for AH2.
I also translate "script.skinvariables" please check it out. 

Anyway I encounter a couple issues while translating AH2:
First one is a missing strings or labels, idk if it in another add-on or not attach to strings.po file?!
the missing strings I found:
```
Revenue\Budget
Released
Returning Series
Ended
Highlight
Gradient
Indicator
Customise Startup image
Full (for "Expand Information")
Plot (for "Expand Information")
Resource Usage (in "Player Process Info")
Memory (in "Player Process Info")
CPU (in "Player Process Info")
```

Second: is a Bug ( Should i report it as "New issue" or on need for that?)
it is RLT bug, in the "Customize Appearance" window the "text" is overlapping on the "toggle buttons" while using Arabic as interface language

image of the Bug:
Screenshot_17

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Thanks, I've fixed up some of the missing strings in latest version of main branch. I can wait for you to translate those if you'd like me to wait before I merge your PR

A few I can't localize because they're either:

- status strings from TMDb and TMDb doesn't provide a translation
- setting strings so need to be hardcoded because it must match setting name

- [x] Revenue\Budget
- [ ] Released [status string]
- [ ] Returning Series [status string]
- [ ] Ended [status string]
- [ ] Highlight [setting string]
- [ ] Gradient [setting string]
- [ ] Indicator [setting string]
- [x] Customise Startup image
- [ ] Full (for "Expand Information") [setting string]
- [ ] Plot (for "Expand Information") [setting string]
- [x] Resource Usage (in "Player Process Info")
- [x] Memory (in "Player Process Info")
- [x] CPU (in "Player Process Info")

I know what the issue is with the Appearance dialog. It's because the label has spaces to avoid overlapping the checkbox but the RTL language reverses the side the spaces appear on (similar issue that the auto-width buttons had originally before I fixed them). I might be able to fix it but not certain.

**Comment by psp2111-ADSLGATE** [comment]
Wow @jurialmunkey, your work is really motivate me and part of me want to learn how to code right now.
I translated the missing strings, and RLT bug is fixed now "image".

I will try to keep the translation updated as much as I can for any added strings in the future.

one last thing, I have an idea which to merge all the different languages fonts into the main and default fonts of the skin.
because when I use Arabic as interface language and switch to AH2 skin, I get a blank interface with no text.
I have to go the settings blindly and change the font from "Default" to "NotoRoboto-Arabic".
I think the same thing will happened to other languages.



Screenshot_18

**Comment by zombiB** [comment]
beautiful work thank you @jurialmunkey and @psp2111-ADSLGATE 
for the universal font i think it is a needed option per example if u watch japanese movies or anime u can't see the title with arabic font
a  possible solution is discussed here  https://github.com/xbmc/xbmc/pull/20552

**Comment by jurialmunkey** [comment]
> Wow @jurialmunkey, your work is really motivate me and part of me want to learn how to code right now. I translated the missing strings, and RLT bug is fixed now "image". Thanks
> 
> I will try to keep the translation updated as much as I can for any added strings in the future.
> 
> one last thing, I have an idea which to merge all the different languages fonts into the main and default fonts of the skin. because when I use Arabic as interface language and switch to AH2 skin, I get a blank interface with no text. I have to go the settings blindly and change the font from "Default" to "NotoRoboto-Arabic". I think the same thing will happened to other languages.
> 

@psp2111-ADSLGATE 

Excellent! Thanks for translating these strings. I'll merge it now. 

Also I'm glad the change I added worked for the spacing on the right. I thought it should in theory but I wasn't 100% sure as Kodi does some weird things sometimes with RTL so it is nice to see that it worked!

Regarding merging all fontsets. It isn't possible. True type fonts have a character limit of 65,535. The CJK fontset is already at that limit by itself. Plus, the more the fonts are merged, the more the baselines and lines heights get messed up.

> for the universal font i think it is a needed option per example if u watch japanese movies or anime u can't see the title with arabic font
> a possible solution is discussed here https://github.com/xbmc/xbmc/pull/20552

@zombiB - Yes unfortunately these are all just workarounds until we have a proper solution for splitting character sets amongst fonts. The current way Kodi handles fontsets is quite bad, and even that PR is still not a great solution but it is better than nothing. 

Ideally Kodi would allow font fallbacks to be defined for individual character sets. Then each individual character set font would be installed and used on an as needed basis. The approach in the PR relies on a mega-font which isn't great as it is several hundred MB but it is at least much better than what is currently available to skins.

**Pull request merged**
