### PR TITLE
Replacing RobotoCondensed-Bold (Bold) with RobotoCondensed-Black.

### PR DESCRIPTION
**Pull request by jbelew**
Please consider this font change. It's derived from the same, 2014 version of RobotoCondensed used by the project so letter styles match. Font height is about 2px smaller than the original font_info_black definition since letters aren't being given the additional bold stroking. I personally think it improves readability since the "counter" forms of the glyphs aren't arbitrarily filled. I attempted using instances extracted from Roboto Flex with wdth=62.5 wght=900, but the results from that approach didn't match nearly as close as the included font.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Needs and Arabic and Hebrew version, otherwise it can't be considered.

**Comment by jbelew** [comment]
Let me add that file to the pull request. I'm not set up to test it effectively though due to the lack of non-English content in my libraries.

**Comment by jurialmunkey** [comment]
Where are you sourcing this from? 

I made the original Hebrew and Arabic font by merging OpenSuse UI based condensed font forms into Roboto Condensed, so it is highly unlikely that you have a comparable source.

**Comment by jbelew** [comment]
Well, I figured out you were punking me on the RobotoNoto ;). I was looking at Noto Sans Condensed Black, and definitely not a match. Black was sourced from here with a change to the build scripts. https://github.com/googlefonts/roboto.

**Comment by jurialmunkey** [comment]
Yeah it is a merged font that I made via fontforge of Roboto and Noto to ensure same linespacing and metrics. Kodi is a complete pain on this front.

I use some OpenSuse modifications of Noto Condensed fonts for Hebrew and Arabic which are more suited to UI rendering, as Arabic in particular can have massive linespacing when tranditional glyph forms are used.

Its a merge of NotoSansArabicUI-Condensed and NotoSansHebrewNew-Condensed and RobotoCondensed. Neither of these fonts are available in the Google font repo anymore (even though it is listed as the source). 
https://fontinfo.opensuse.org/fonts/NotoSansArabicUICondensedBold.html
https://fontinfo.opensuse.org/fonts/NotoSansHebrewNewCondensedMedium.html

**Comment by jbelew** [comment]
I just did some testing on font size variation. It's an across-the-board 2px decrease in height for the Black font for all the sizes down to 32. The 2px is coming from the stroke the Kodi font rendering engine is adding. You referenced a similar observation in your comments in the Font.xml file.

**Comment by jurialmunkey** [comment]
The comment is the fonts file is about the actual fonts themselves, not the Kodi "bold" style -- but in effect it is ultimately the same idea in reverse.

In the Roboto font, the Bold and Regular have the same x-height. The Bold version "feels" smaller as a result because Google shrinks the lines so that the additional stroke width will stay *inside* the x-height bounds. To address that change in feel, I then shrink the Regular font 2pts.

By contrast (and as you observe), the Kodi "bold" style applies expands the font *outside* the x-height bounds to accomodate the additional stroke width. That maintains the "feel" but changes the actual height.

So in fact I'm not applying my rule properly to those Bold+"Bold" hacks for the black style. They should actually be shrunk 2pts -- and what you're seeing in your PR with the real Black font is closer to what the height should actually be.

All that being said, whilst the Black font is clearer I don't think it is heavy enough. I think it is only 900 weight when the Bold+Bold is more around 1000 (Regular to Bold is 400 to 700, so next step should be 1000 not 900).

**Comment by jbelew** [comment]
Yeah, is actually Extra Bold, 800 since you were doing bold + bold. Above 800, it really starts preventing the Condensed effect.

**Comment by jbelew** [comment]
Thanks for putting up with me. This is the first time I've actually done a PR for an open-source project.

**Comment by jurialmunkey** [comment]
No worries! 

I would've pushed my updated fonts for Arabic and Hebrew back to this PR to keep the history but thought it'd be easier for others to test if I made a new PR with everythign squashed into one commit.

I think it is a good improvement - just need to make sure that I sort out the Arabic/Hebrew support too and that the new font I've made from this one isn't introducing any issues on that front. I'll merge into the main branch once psp2111-ADSLGATE has tested in Arabic and confirmed that everything looks good there.

**Comment by jbelew** [comment]
I'll see if I can make an effective, 900, condensed using a different process tomorrow.

**Pull request closed without merging**
