### PR TITLE
Add display of episodes in current season for library content recommendations

### PR DESCRIPTION
**Pull request by MoojMidge**
For consideration.

I mainly have local library content and it is a little cumbersome to get season and other episode details from recently added episodes and similar widgets.

### CODE REVIEW

**Comment by MoojMidge** [comment]
Some screenshots showing what this PR actually does for the Collection widget when using library only recommendations.

Previously the Collection widget only worked on movies and tvshows. This PR extends the existing functionality to also work for episodes and single season shows.

Info dialog for TV show with multiple seasons - showing all seasons in poster view. Clicking on a season will open the season browse view. As per existing functionality.
image

Info dialog for TV show with single season - showing all episodes for single season in landscape view with expanded info if Recommendations.ExpandPlot setting is enabled. Clicking on an episode will re-open the info dialog for the selected episode.
image

Info dialog for Single episode - showing all episodes in the same season in landscape view with expanded info if Recommendations.ExpandPlot setting is enabled. Clicking on an episode will re-open the info dialog for the selected episode.
image

**Comment by jurialmunkey** [comment]
Yeah I think this will be a great addition. Code looks fine from a quick look - I just need to give it a test drive first.

A very minor point - the label should be changed to "Episodes" with a variable for Episodes  (same goes for "Seasons" - I think I forgot to do that)

Also, this PR will close #165 (albeit via a different method)

**Comment by jurialmunkey** [comment]
^^^ Those commits I just pushed will fix the labels and also add a couple of improvements.

Same behaviour as before but with the addition that if you go to a tvshow/season with multiple seasons then the episodes container will display under the "seasons" collection and display the episodes for the currently focused season in the container.

Also, it might be due to differences how different OS handles filepaths, but on Windows the episode onclick action wasn't working properly for me so I switched it for a different method (based the rules on TVShowTitle+Season+Episode rather than FileName+Path).

Finally, I removed your ?xsp= parts of the paths. No harm in them being there but they don't really do anything.

Can you give it a test run and make sure these additions work correctly for you?

**Comment by MoojMidge** [comment]
Looks good with the ability to select a season.

> A very minor point - the label should be changed to "Episodes" with a variable for Episodes (same goes for "Seasons" - I think I forgot to do that)

I was actually thinking whether to make the episodes widget say "Up Next" and also use the DisableUpNext setting to mirror what is used when TMDBHelper recommendations are used? At moment I used the DisableSeasons settings for the new local recommendations episodes widget, which means the functionality is a little different if local or TMDBHelper recommendations are used.

The only problem with using the DisableUpNext setting is that it would be in a different order/location compared to the local recommendations episodes widget in the info dialog. Could change the order of the recommendation settings and the TMDBHelper recommendation window xml (also create a matching PR for TMDBHelper), as I think the "Up Next" (episodes) widget should logically be presented along with the "Seasons" widget (similar to what you added to show the episodes of the selected season), but I don't know whether the change is necessary?

> Finally, I removed your ?xsp= parts of the paths. No harm in them being there but they don't really do anything.

I added the xsp query solely to order the results. Otherwise the listing is ordered by date added to the library (I think), which may not necessarily be the correct episode order, if for example library info is refreshed and/or files are updated.

**Comment by MoojMidge** [comment]
Added a new commit to order the contents of the episode widget rather than using the xsp query in the paths

**Comment by jurialmunkey** [comment]
> Added a new commit to order the contents of the episode widget rather than using the xsp query in the paths

Ah I didn't realise they were sorted by date added - I guess all my library content that I tested with was added in airing order.

I think content tag sorting like you've added here is probably a better approach anyway because then it works for every path.

> I was actually thinking whether to make the episodes widget say "Up Next" and also use the DisableUpNext setting to mirror what is used when TMDBHelper recommendations are used? 

The Up Next widget from TMDbHelper is a little different. It's a special season folder which calculates which episodes the user should watch next based upon their Trakt watched history.

For instance, if the user has watched up to S03E07 then UpNext will display unwatched episodes from S03E08 onwards. It also takes into account rewatches - e.g. if you started a second watch of the show it will count every episode with only 1 watch as if it were unwatched; and if you watched everything then it will display from S01E01 again.

I'm not sure if there's an equiavlent possible via a smart playlist. Maybe could get close using an all episodes list where playcount=0

**Comment by jurialmunkey** [comment]
Anyway I think this is good for now - I'll merge it so it can go into the next release I'm about to push. Then we can think about incorporating something with the UpNext setting afterwards.

**Comment by MoojMidge** [comment]
> The Up Next widget from TMDbHelper is a little different.

Yeah I know, was just was initially wondering if the DisableSeason setting was the correct one to use, since the TMDBHelper recommendations don't show the episodes widget along with the collections/seasons widget, and the closest in functionality was the TMDB Up Next widget.

I think it is fine as-is given the limitations of the library and xsp queries. Thanks

**Pull request merged**
