### PR TITLE
Add missing DefaultPartyMode.png

### PR DESCRIPTION
**Pull request by berkhornet**
The default party mode icon is missing from the /media directory; a blank space appears in the music library where it is expected

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Nice. I like the icon. Where is it from? Need to check the license is compatible.

**Comment by berkhornet** [comment]
Hi

I found the icon with the standard Estuary skin.

Cheers

**Comment by jurialmunkey** [comment]
Actually the scaling of the icon looks a bit rough when I use the square aspect. Lots of jagged aliasing on the arm. I like the icon itself (and license would be fine since it is from Estuary) -- but that jagged edge is not great

I might go with this icon from iconmonstr instead:
https://iconmonstr.com/party-15-png/

**Comment by berkhornet** [comment]
Hi. That one looks great! Works for me.

Mick
________________________________

**Pull request closed without merging**
