### PR TITLE
Alternative Fonts for Arabic Language

### PR DESCRIPTION
**Pull request by psp2111-ADSLGATE**
Hi @jurialmunkey this is a better Arabic Fonts in my opinion for AH2.
I merged the fonts with RobotoCondensed using FontForge.

I also changed the font size for "font_infotitle" and "font_infotitle_light" from 78 to 67.

Before

Screenshot_12
Screenshot_13

After

Screenshot_14
Screenshot_15

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Amazing! Thanks. 

I'll have a proper look later today after work before merging but judging from the screenshots these changes look really good!

**Comment by jurialmunkey** [comment]
@psp2111-ADSLGATE -- I think I've managed to come up with a solution that solves the baseline issue and keeps title sizing.

Could you try the version from the `noto_arabic_ui` branch and let me know if there are any issues using the NotoRoboto fontset
https://github.com/jurialmunkey/skin.arctic.horizon.2/archive/refs/heads/noto_arabic_ui.zip

As far as I can tell, it looks good to me but I'm not an Arabic speaker.

Example using Fantastic Beasts:

Honeyview_screenshot00061

**Comment by psp2111-ADSLGATE** [comment]
so far the baseline issue seems to be resolved, I tried both "bold" and "thin" fonts quickly for most of the viewtypes , Fullscreen widget and Information window it looks good with no half letters anymore.

but I found a big issue, the "Titles" and "Plot" for main menu "widgets" are gone now, I made sure that "Expand Information" set to "Full" or "Plot" nothing show up for neither.
at first I thought it was an Arabic fonts issue, so I changed kodi and everything back to English and used the "Default" Font of AH2 but still no info show up for the widgets.

it is like the "Expand Information" feature not working anymore?!

Image for the issue
Screenshot_16

**Comment by jurialmunkey** [comment]
Ah yep can confirm the widget info issue and I know what the issue is so was easy to fix. Thanks for pointing that out - I forgot to test the widgets.

I think that should be everything, so I'll merge.

**Pull request closed without merging**
